//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace LearnHub
{
	/// <summary>
	/// Represents a page of type <see cref="Course"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Course : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "LearnHub.Course";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// CourseTeacherName.
		/// </summary>
		public string CourseTeacherName { get; set; }


		/// <summary>
		/// CourseTitle.
		/// </summary>
		public string CourseTitle { get; set; }


		/// <summary>
		/// CourseDuration.
		/// </summary>
		public string CourseDuration { get; set; }


		/// <summary>
		/// CourseFollowers.
		/// </summary>
		public decimal CourseFollowers { get; set; }


		/// <summary>
		/// CourseStars.
		/// </summary>
		public decimal CourseStars { get; set; }


		/// <summary>
		/// CoursePrice.
		/// </summary>
		public decimal CoursePrice { get; set; }


		/// <summary>
		/// ButtonName.
		/// </summary>
		public string ButtonName { get; set; }


		/// <summary>
		/// ButtonLink.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> ButtonLink { get; set; }


		/// <summary>
		/// CourseThumbnail.
		/// </summary>
		public IEnumerable<Assets> CourseThumbnail { get; set; }
	}
}