//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace LearnHub
{
	/// <summary>
	/// Represents a page of type <see cref="Testimonial"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Testimonial : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "LearnHub.Testimonial";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// TestimonialName.
		/// </summary>
		public string TestimonialName { get; set; }


		/// <summary>
		/// TestimonialDescription.
		/// </summary>
		public string TestimonialDescription { get; set; }


		/// <summary>
		/// TestimonialJobDescription.
		/// </summary>
		public string TestimonialJobDescription { get; set; }


		/// <summary>
		/// TestimonialStars.
		/// </summary>
		public decimal TestimonialStars { get; set; }


		/// <summary>
		/// TestimonialThumbnail.
		/// </summary>
		public IEnumerable<Assets> TestimonialThumbnail { get; set; }
	}
}