//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace LearnHub
{
	/// <summary>
	/// Represents a page of type <see cref="Price"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Price : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "LearnHub.Price";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// PriceTitle.
		/// </summary>
		public string PriceTitle { get; set; }


		/// <summary>
		/// PriceDescription.
		/// </summary>
		public string PriceDescription { get; set; }


		/// <summary>
		/// PricePerMonth.
		/// </summary>
		public decimal PricePerMonth { get; set; }


		/// <summary>
		/// PriceItemList.
		/// </summary>
		public string PriceItemList { get; set; }


		/// <summary>
		/// ButtonName.
		/// </summary>
		public string ButtonName { get; set; }


		/// <summary>
		/// ButtonLink.
		/// </summary>
		public IEnumerable<WebPageRelatedItem> ButtonLink { get; set; }
	}
}