//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS.ContentEngine;
using CMS.Websites;

namespace LearnHub
{
	/// <summary>
	/// Represents a page of type <see cref="Mentor"/>.
	/// </summary>
	[RegisterContentTypeMapping(CONTENT_TYPE_NAME)]
	public partial class Mentor : IWebPageFieldsSource
	{
		/// <summary>
		/// Code name of the content type.
		/// </summary>
		public const string CONTENT_TYPE_NAME = "LearnHub.Mentor";


		/// <summary>
		/// Represents system properties for a web page item.
		/// </summary>
		[SystemField]
		public WebPageFields SystemFields { get; set; }


		/// <summary>
		/// MentorName.
		/// </summary>
		public string MentorName { get; set; }


		/// <summary>
		/// MentorTitle.
		/// </summary>
		public string MentorTitle { get; set; }


		/// <summary>
		/// MentorDescription.
		/// </summary>
		public string MentorDescription { get; set; }


		/// <summary>
		/// MentorFollowers.
		/// </summary>
		public decimal MentorFollowers { get; set; }


		/// <summary>
		/// MentorCourses.
		/// </summary>
		public int MentorCourses { get; set; }


		/// <summary>
		/// FirstLinkIcon.
		/// </summary>
		public string FirstLinkIcon { get; set; }


		/// <summary>
		/// FirstButtonLink.
		/// </summary>
		public string FirstButtonLink { get; set; }


		/// <summary>
		/// SecondLinkIcon.
		/// </summary>
		public string SecondLinkIcon { get; set; }


		/// <summary>
		/// SecondButtonLink.
		/// </summary>
		public string SecondButtonLink { get; set; }


		/// <summary>
		/// MentorThumbnail.
		/// </summary>
		public IEnumerable<Assets> MentorThumbnail { get; set; }


		/// <summary>
		/// MentorStars.
		/// </summary>
		public decimal MentorStars { get; set; }


		/// <summary>
		/// ThirdLinkIcon.
		/// </summary>
		public string ThirdLinkIcon { get; set; }


		/// <summary>
		/// ThirdButtonLink.
		/// </summary>
		public string ThirdButtonLink { get; set; }
	}
}